### ISSUE TITLE
build fails on CURRENT and FreeBSD 11.3 (BETA)

### ISSUE THREAD

**Issue by pizzamig** [tagattie/FreeBSD-Electron#8] opened 2019-06-05 11:13 UTC
The build fails on CURRENT (AKA FreeBSD 13)
This is the log:
http://beefy12.nyi.freebsd.org/data/head-amd64-default/p503433_s348595/logs/errors/electron4-4.2.2.log

This can be caused by a newer c++ toolchain that will be likely adopted by the coming 11.3 and 12.1

**Comment by tagattie** [comment] 2019-06-06 09:08
Hi @pizzamig,

Thanks for letting me know this. According to the log, it appears the c++ compiler picks up `${WRKSRC}/out/Release/version` instead of `/usr/include/c++/v1/version` :frowning_face:.

Now I'm setting up a CURRENT build environment...

**Comment by pizzamig** [comment] 2019-06-06 14:05
I've just tried to build electron on FreeBSD 11.3 (BETA2), that share the same toolchain of CURRENT and it's less demanding to install on poudriere
`poudriere jails -c -j 113x64b2 -v 11.3-BETA2` will do
The error produced is exactly the same

**Comment by tagattie** [comment] 2019-06-07 04:46
I pushed some changes to the `Makefile` to unbreak builds on CURRENT and 11.3.

The source of the problem is a conflict of the filename (`version`) generated in `${WRKSRC}/out/Release` with the one in standard C++ include paths.

The changes make the build process generate the `version` file at the very end of the process to avoid such conflict.

**Comment by pizzamig** [comment] 2019-06-07 08:34
I'm testing 4.2.4 on all jails available to me.
If the build is OK, I'll commit it to the portstree.

**Comment by tagattie** [comment] 2019-06-18 11:33
It appears both builds on CURRENT amd64 and i386 are successful according to the following URLs:
- http://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/electron4-4.2.4.txz
- http://pkg.freebsd.org/FreeBSD:13:i386/latest/All/electron4-4.2.4.txz

I presume now builds on 11.3 (amd64, i386) will also succeed. So I close this issue.

Thanks @pizzamig for your efforts and time on this issue :smile:

**Closed by tagattie** 2019-06-18 11:33 UTC

**Comment by pizzamig** [comment] 2019-06-19 15:57
yep, sorry, I did the commit without closing this issue :D
